(import 'actuator-mixin/mixin.libsonnet')
+ (import 'core-mixin/mixin.libsonnet')
+ (import 'camera-mixin/mixin.libsonnet')
+ (import 'display-mixin/mixin.libsonnet')
+ (import 'light-mixin/mixin.libsonnet')
+ (import 'sensor-mixin/mixin.libsonnet')
+ (import 'vendor-mixin/mixin.libsonnet')
+ (import 'auto-mixin/mixin.libsonnet')
